# Generated by Django 5.2.6 on 2025-09-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
