# Generated by Django 5.2.6 on 2025-09-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=120)),
                ('primary_color', models.CharField(default='#0ea5e9', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
            ],
        ),
    ]
