# Generated by Django 5.2.7 on 2025-10-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(blank=True, max_length=540),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=360),
        ),
    ]
