# Generated by Django 5.2.7 on 2025-10-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_alter_post_summary_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
