# Generated by Django 5.2.7 on 2025-11-19 21:35

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='URL do vídeo (YouTube/Vimeo)'),
        ),
    ]
