# Generated by Django 5.2.7 on 2025-11-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.TextField(blank=True, help_text='Cole aqui o código completo do iframe do vídeo (YouTube/Vimeo)'),
        ),
    ]
