# Generated by Django 5.2.7 on 2025-11-27 00:49

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0009_alter_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='URL do vídeo (YouTube/Vimeo)'),
        ),
    ]
