# Generated by Django 5.2.7 on 2025-11-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0010_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
