# Generated by Django 5.2.7 on 2025-11-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0011_sitesettings_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(max_length=120, verbose_name='Nome do site'),
        ),
    ]
