# Generated by Django 5.2.7 on 2025-12-05 09:08

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0012_alter_sitesettings_site_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField(blank=True, verbose_name='Resumo curto')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descrição completa')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo para venda?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso/Treinamento',
                'verbose_name_plural': 'Cursos e Treinamentos',
            },
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'verbose_name': 'Inscrito na newsletter', 'verbose_name_plural': 'Inscritos na newsletter'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Configuração do site', 'verbose_name_plural': 'Configurações do site'},
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='client_app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
