# Generated by Django 5.2.7 on 2025-12-17 07:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0013_course_alter_newslettersubscriber_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Conteúdo visível apenas para alunos', verbose_name='Descrição completa'),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.TextField(blank=True, help_text='Aparece no card do curso', verbose_name='Resumo curto'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Matrícula'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pago / Acesso Liberado'),
        ),
    ]
