# Generated by Django 5.2.7 on 2025-12-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0014_alter_course_cover_image_alter_course_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('profession', models.CharField(max_length=100, verbose_name='Profissão')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('phone', models.CharField(max_length=20, verbose_name='Celular/Whatsapp')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('zip_code', models.CharField(max_length=20, verbose_name='CEP')),
                ('admin_region', models.CharField(max_length=100, verbose_name='Região Administrativa')),
                ('electoral_zone', models.CharField(max_length=20, verbose_name='Zona eleitoral')),
                ('section', models.CharField(max_length=20, verbose_name='Seção')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apoiador',
                'verbose_name_plural': 'Apoiadores',
                'ordering': ['-created_at'],
            },
        ),
    ]
