# Generated by Django 5.2.7 on 2025-12-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0015_supporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supporter',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
